version: '3'

services:
  # Weatherstation system
  system:
    container_name: system
    image: gcr.io/cycloneport/system:0.0.6
    restart: on-failure
    privileged: true
    network_mode: "host"
    cap_add:
      - ALL
    volumes:
      - ./info.json:/app/info.json
      - ./.env:/app/.env
      - ./data:/data
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /var/log:/var/log
      - /etc/dhcpcd.conf:/etc/dhcpcd.conf
      - /etc/udev/rules.d:/etc/udev/rules.d
      - /tmp/cycloneport-execpipe:/pipes/exec
  
  # Reverse proxy
  caddy:
    container_name: caddy
    image: gcr.io/cycloneport/caddy:0.0.1
    restart: on-failure
    network_mode: "host"
