version: '3'

services:
  # Video capabilities
  # USB cam support
  usb_cam:
    container_name: usb_cam
    image: gcr.io/cycloneport/usb_cam:0.0.4
    restart: on-failure
    network_mode: "host"
    volumes:
      # This is required to access USB devices from inside the container
      - /dev:/dev
      - /run/udev:/run/udev:ro
    privileged: true

  # Net cam support
  net_cam:
    container_name: net_cam
    image: gcr.io/cycloneport/net_cam:0.0.16
    restart: on-failure
    network_mode: "host"
    volumes:
      - "${WS_ROOT}/data:/data"
      - "${WS_ROOT}/.env:/weatherstation/.env"
    tmpfs:
      - /app/media
    privileged: true

  # Video manager
  video_manager:
    container_name: video_manager
    image: gcr.io/cycloneport/video_manager:0.0.5
    restart: on-failure
    network_mode: "host"
    volumes:
      - "${WS_ROOT}/data:/data"
      - "${WS_ROOT}/.env:/weatherstation/.env"
