version: '3'

services:
  # Weatherstation system
  system:
    container_name: system
    image: gcr.io/cycloneport/system:0.0.8
    restart: on-failure
    privileged: true
    network_mode: "host"
    environment:
      WS_ROOT: "${WS_ROOT}"
    cap_add:
      - ALL
    volumes:
      - "${WS_ROOT}/info.json:/app/info.json"
      - "${WS_ROOT}/.env:/app/.env"
      - "${WS_ROOT}/data:/data"
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /var/log:/var/log
      - /etc/dhcpcd.conf:/etc/dhcpcd.conf
      - /etc/udev/rules.d:/etc/udev/rules.d
      - /tmp/cycloneport-execpipe:/pipes/exec
  
  # Reverse proxy
  caddy:
    container_name: caddy
    image: gcr.io/cycloneport/caddy:0.0.1
    restart: on-failure
    network_mode: "host"
