version: '3'

services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.1.1
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 127.0.0.1:8888:8080
    environment:
      - DOZZLE_BASE=/debug/logs
