version: '3'

services:
  # WiFi API
  txwifi:
    container_name: txwifi
    image: gcr.io/cycloneport/txwifi:0.0.3
    restart: on-failure
    privileged: true
    network_mode: "host"
    volumes:
      - /etc/wpa_supplicant/:/etc/wpa_supplicant/
