#!/bin/bash

# Must be run as root
if [[ "$EUID" -ne 0 ]]; then
	echo
	echo "Please run as root"
	echo
	exit 1
fi

dev_name="ttyGPS"
last_usb_num=$(echo "${1}" | grep -Eo '[0-9]+$')

echo "${dev_name}${last_usb_num}"