#!/bin/bash

export WS_ROOT="$(realpath $(readlink -f $(dirname "${BASH_SOURCE[0]}"))/..)"

dotenv="${WS_ROOT}/.env"

# Must be run as root
if [[ "$EUID" -ne 0 ]]; then
	echo
	echo "Please run as root"
	echo
	exit 1
fi

dev="/dev/${1}"

#echo "Dev: ${dev}"

stty -F "${dev}" raw
stty -F "${dev}" -echo

# First try to detect Boltek ERL10
# Which uses 115200 baud rate
stty -F "${dev}" 115200

read_anything=0
while [[ "${read_anything}" -lt 20 ]]; do
    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        #echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]]; then
            break
        fi
        line="${line}${char}"
        #read_anything=1
    done < "${dev}"
    ((read_anything=read_anything+1))
    #echo

    # If the line contains any Boltek keywords, then we know the serial device is connected to a Boltek system
    if [[ "${line}" == *"@ST"* ]] || [[ "${line}" == *"@WT"* ]] || [[ "${line}" == *"@HR"* ]]; then
        echo "ttyBoltekERL10"
        exit
    fi
done

stty -F "${dev}" raw
stty -F "${dev}" -echo

# Set the baud rate
stty -F "${dev}" 9600

read_anything=0
while [[ "${read_anything}" -lt 300 ]]; do
    # Send a 'R' for Hydreon RG15 rain guages to respond
    echo -ne "R\r\n" > "${dev}"

    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        #echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]]; then
            break
        fi
        line="${line}${char}"
        #read_anything=1
    done < "${dev}"
    if ! [[ -z "${line}" ]]; then
        #echo "line: ${line}"
        ((read_anything=read_anything+1))
    fi
    #echo

    # If the line contains any Boltek keywords, then we know the serial device is connected to a Boltek system
    if [[ "${line}" == *"WIMST"* ]] || [[ "${line}" == *"WIMLI"* ]] || [[ "${line}" == *"WIMLN"* ]]; then
        echo "ttyBoltekLD250"
        exit
    elif [[ "${line}" == *"RInt"* ]] || [[ "${line}" == *"HYDREON"* ]]; then
        echo "ttyHydreon"
        exit
    # Wait for alteast 30 cycles and then lastly we'll assume it's a Young Weather Transmitter
    elif [[ "${read_anything}" -gt 20 ]] && [[ "${line}" == *" "* ]]; then
        echo "ttyYoung"
        exit
    fi
done