#!/bin/bash

# Must be run as root
if [[ "$EUID" -ne 0 ]]; then
	echo
	echo "Please run as root"
	echo
	exit 1
fi

dev="/dev/${1}"

#echo "Dev: ${dev}"

stty -F "${dev}" raw
stty -F "${dev}" -echo

# Set the baud rate
stty -F "${dev}" 9600

read_anything=0
while [[ "${read_anything}" -lt 300 ]]; do
    line=""
    while IFS= read -d '' -t .5 -rn1 char;do
        #echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]]; then
            break
        fi
        line="${line}${char}"
        #read_anything=1
    done < "${dev}"
    if ! [[ -z "${line}" ]]; then
        #echo "line: ${line}"
        ((read_anything=read_anything+1))
    fi
    #echo

    # If the line contains any Boltek keywords, then we know the serial device is connected to a Boltek system
    if [[ "${line}" == *"WIMST"* ]] || [[ "${line}" == *"WIMLI"* ]] || [[ "${line}" == *"WIMLN"* ]]; then
        echo "ttyBoltek"
        exit
    # Else we'll assume it's a Young Weather Transmitter
    elif [[ "${line}" == *" "* ]]; then
        echo "ttyYoung"
        exit
    fi
done