#!/bin/bash

export WS_ROOT="$(realpath $(readlink -f $(dirname "${BASH_SOURCE[0]}"))/..)"

dotenv="${WS_ROOT}/.env"

if [[ -f "${dotenv}" ]]; then
	set -o allexport
	source "${dotenv}" set
	set +o allexport
fi

# Must be run as root
if [[ "$EUID" -ne 0 ]]; then
	echo
	echo "Please run as root"
	echo
	exit 1
fi

# This script runs for USB devices with idVendor = 067b
# But we can redirect to another script...
if [[ -n "${DEV_067b}" ]]; then
	if [[ "${DEV_067b}" == "0403_6001" ]]; then
		"${WS_ROOT}/scripts/dev-Boltek-Young-namer" "${1}"
		exit
	elif [[ "${DEV_067b}" == "0403_6015" ]]; then
		"${WS_ROOT}/scripts/dev-RenogyControl-namer" "${1}"
		exit
	elif [[ "${DEV_067b}" == "10c4_ea60" ]]; then
		"${WS_ROOT}/scripts/dev-LoRa-namer" "${1}"
		exit
	fi
fi

serial_name="${1}"
last_usb_num=$(echo "${serial_name}" | grep -Eo '[0-9]+$')

dev="/dev/${serial_name}"

stty -F "${dev}" raw
stty -F "${dev}" -echo

# First try to detect Boltek ERL10
# Which uses 115200 baud rate
stty -F "${dev}" 115200

read_anything=0
read_char=0
while [[ "${read_anything}" -lt 10 ]]; do
    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        #echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]] || [[ "${read_char}" -gt 300 ]]; then
            break
        fi
        line="${line}${char}"
        ((read_char=read_char+1))
    done < "${dev}"
    ((read_anything=read_anything+1))
    #echo

    # If the line contains any Boltek keywords, then we know the serial device is connected to a Boltek system
    if [[ "${line}" == *"@ST"* ]] || [[ "${line}" == *"@WT"* ]] || [[ "${line}" == *"@HR"* ]]; then
        echo "ttyBoltekERL10"
        exit
    fi
done

stty -F "${dev}" raw
stty -F "${dev}" -echo

# Set the baud rate
stty -F "${dev}" 9600

read_anything=0
while [[ "${read_anything}" -lt 10 ]]; do
    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        # echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]]; then
            break
        fi
        line="${line}${char}"
        # read_anything=1
    done < "${dev}"
    if ! [[ -z "${line}" ]]; then
        # echo "line: ${line}"
        ((read_anything=read_anything+1))
    fi
    # echo

    # If the line contains any Boltek keywords, then we know the serial device is connected to a Boltek system
    if [[ "${line}" == *"WIMST"* ]] || [[ "${line}" == *"WIMLI"* ]] || [[ "${line}" == *"WIMLN"* ]]; then
        echo "ttyBoltekLD250"
        exit
    fi
done

dev_name="ttyGPS"
last_usb_num=$(echo "${1}" | grep -Eo '[0-9]+$')

echo "${dev_name}${last_usb_num}"