#!/bin/bash

export WS_ROOT="$(realpath $(readlink -f $(dirname "${BASH_SOURCE[0]}"))/..)"

dotenv="${WS_ROOT}/.env"

# Must be run as root
if [[ "$EUID" -ne 0 ]]; then
	echo
	echo "Please run as root"
	echo
	exit 1
fi

serial_name="${1}"
last_usb_num=$(echo "${serial_name}" | grep -Eo '[0-9]+$')

dev="/dev/${serial_name}"

#echo "Dev: ${dev}"

# First we try to detect LoRa hardware (896 or 998)
# Using the baud rate 115200
stty -F "${dev}" raw
stty -F "${dev}" -echo
stty -F "${dev}" 115200

read_anything=0
read_char=0
while [[ "${read_anything}" -lt 6 ]]; do
    echo -ne "AT\r\n" > "${dev}" &
    echo -ne "ATZ\r\n" > "${dev}" &

    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        # echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]] || [[ "${read_char}" -gt 300 ]]; then
            break
        fi
        line="${line}${char}"
        ((read_char=read_char+1))
    done < "${dev}"
    ((read_anything=read_anything+1))
    #echo
    
    wait

    # If the line contains any MT WS keywords
    if [[ "${line}" == *"OK"* ]] || [[ "${line}" == *"ERR"* ]]; then
        echo "ttyLoRa${last_usb_num}"
        exit
    fi
done

# Secondly we set the baud rate to 9600 to try detect
# MT WS devices or LoRa hardware (993)
stty -F "${dev}" raw
stty -F "${dev}" -echo
stty -F "${dev}" 9600

read_anything=0
read_char=0
while [[ "${read_anything}" -lt 20 ]]; do
    echo -ne "AT\r\n" > "${dev}" &
    echo -ne "ATZ\r\n" > "${dev}" &

    line=""
    while IFS= read -d '' -t .5 -rn1 char; do
        # echo -n "${char}"
        if [[ "${char}" == *$'\n'* ]] || [[ "${read_char}" -gt 300 ]]; then
            break
        fi
        line="${line}${char}"
        ((read_char=read_char+1))
    done < "${dev}"
    ((read_anything=read_anything+1))
    #echo

    wait

    # If the line contains any MT WS keywords
    if [[ "${line}" == "PLD="* ]]; then
        echo "ttyWS${last_usb_num}"
        exit
    elif [[ "${line}" == *"REYAX"* ]] || [[ "${line}" == *"OK"* ]] || [[ "${line}" == *"ERR"* ]]; then
        echo "ttyLoRa${last_usb_num}"
        exit
    fi
done

# Failing all this, we'll assume MT WS hardware
echo "ttyWS${last_usb_num}"
